"""Enums for field status, alert severity, and alert types."""

from enum import Enum


class FieldStatus(str, Enum):
    """Field irrigation status - maps to dashboard colors (green/orange/red)."""
    OK = "ok"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertSeverity(str, Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertType(str, Enum):
    """Types of alerts generated by the system."""
    IRRIGATION = "irrigation"
    STRESS = "stress"
    SYSTEM = "system"
